### ISSUE TITLE
plugin does not work with Smarty 3.1.28

### ISSUE THREAD

**Issue by gtraxx** [pynej/Smarty-Switch-Statement#1]
Hi, your plugin does not work with Smarty 3.1.28
Fatal error: Call to undefined method Smarty_Internal_Method_LoadPlugin::registerFilter()
If I correct this error the other displays
View new smarty version : https://github.com/smarty-php/smarty

Best Regards

**Comment by kkrolikowski** [comment]
I can confirm that it works up to v3.1.27

**Comment by gtraxx** [comment]
Yes with v3.1.27 but not work with Smarty 3.1.28

**Comment by pynej** [comment]
This plugin has been updated to be compatible.  Note that you will need to update your plugin file AND add a line to your smarty loading code to register a second module as I am unable to do it internally in the plugin.

**Comment by michabbb** [comment]
just a note: it´s working with 3.1.33 ℹ️
